### ISSUE TITLE
PNI Contractor page on Wagtail

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#736]
Placeholder ticket for making the PNI contractor page on Wagtail.

Context: Met with Sabrina and Kristina last week about creating brand pages on Wagtail specifically for MozFest, PNI, and Trustworthy AI. 

Structure is as follows:
Overview
Intro sentence
Audience

Working files and visual components
Links
Colors
Type
Icons
Etc.

Expressions
In situ examples
Seasonal themes
Moodboards
Etc.

Web design
Link to figma

**Comment by natalieworth** [comment]
I have the outline and have added some visual components to Wagtail and updated it to be inline with Sabrina's styling and outline. I need to add the links and expressions but need to update the .ai files so they're okay for contractor hand-off. (e.g. past marketing files, and the Valentine's, holiday, and evergreen versions).

**Comment by natalieworth** [comment]
I updated the main/ [overview contractor page](https://foundation.mozilla.org/en/docs/brand/agency-assets/) (removed the PNI specific area and added a general 'themes' area)

I also published the PNI [theme page here](https://foundation.mozilla.org/en/docs/brand/design/theme-page-privacy-not-included/).

**Comment by kristinashu** [comment]
@natalieworth re-opening this because I still see some PNI references that need to be removed e.g. PNI colors here https://foundation.mozilla.org/en/docs/brand/design/color/

**Comment by natalieworth** [comment]
Adding that we should add the guidelines around doing 1 off/ seasonal campaigns and the design and brand variations.

**Comment by kristinashu** [comment]
Since you didn't end up changing the logo, I don't think you need to justify things too too much. 

To close this ticket I'd say the remaining work is:
- [ ] Remove PNI references from other brand page
- [ ] Add v-day 2021 references

**Comment by kristinashu** [comment]
Looks good but you still just need to:

- [ ] Remove the pni colors from here https://foundation.mozilla.org/en/docs/brand/design/color/

- [ ] "Valentine's Day 2021" should link to parent folder (not the contractor assets).
![image.png](https://images.zenhubusercontent.com/568fffdd638e718c995fe973/ec65ddbb-2462-4487-9159-586562207fd9)

- [ ] "*Privacy Not Included word mark" link would be better if it linked to a folder with both the black and the white version of the logo.

**Comment by natalieworth** [comment]
[Theme page updated here](https://foundation.mozilla.org/en/docs/brand/design/theme-page-privacy-not-included/). I ended up making a Valentine's 2021 folder with no viewing restrictions for contractors and then we have our original/ process/ exported files only viewable to Mozilla accounts still. Does that work or do you think it's better to have all the files viewable?

**Comment by kristinashu** [comment]
Yup that works! I doubt very many contractors will need access and it's no problem to give them access as needed.

**Comment by kristinashu** [comment]
I think this is good to close?

**Comment by natalieworth** [comment]
yea :D
